### ISSUE TITLE
Jekyll plugins

### ISSUE THREAD

**Issue by sawyerh** [siteleaf/learn.siteleaf.com#44]
We seem to get asked often about what Jekyll plugins we support. I'm actually not super clear on the answer to this...cc @larryfox @sskylar

**Comment by larryfox** [comment]
We support these: https://pages.github.com/versions/

**Comment by sawyerh** [comment]
Cool, we should add this to the docs. cc @eturk

**Comment by eturk** [comment]
We have a few options here on how to get this content into the docs:

1. Just manually write out what we support. We'll need to go in and update the docs every time we/GitHub updates a dependency
2. Use [GitHub's version JSON endpoint](https://pages.github.com/versions.json) to generate a list. However, we don't support `jekyll-github-metadata` and we use a different Ruby version.
3. Roll our own JSON endpoint. But, [we're going to be adopting the `github-pages` Gem soon, so that may not matter](https://oak.slack.com/archives/siteleaf/p1458837630000014).
4. Make a bot that listens to [Jekyll's bot](https://github.com/github/pages-gem/pull/260) that notifies them of new dependency versions.
5. ???

**Comment by sskylar** [comment]
Can mention #45 for advanced users
